services:
  kudos-bot:
    build: .
    container_name: kudos-bot
    env_file:
      - .env
    volumes:
      - kudos_db:/data
      - ./exports:/exports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  kudos_db:
